### ISSUE TITLE
Filtering & bulk editing of endpoints 

### ISSUE THREAD

**Issue by nclavric** [CiscoDevNet/iPSK-Manager#19]
**Is your feature request related to a problem? Please describe.**
To be honest... I don't think so :)

**Describe the solution you'd like**
It would be nice if you could filter or search for all configured endpoints using one or more attributes and carry out mass changes or deletions on them.

**Describe alternatives you've considered**
Such changes are currently only possible with direct database access. However, this is not a viable solution for the actual portal users and contradicts the actual purpose of the portal..

**Comment by David00** [comment]
@nclavric - Searching the table is a feature I've been wanting for a while too now... so I just built it.  See https://github.com/CiscoDevNet/iPSK-Manager/pull/22

**Comment by nclavric** [comment]
> @nclavric - Searching the table is a feature I've been wanting for a while too now... so I just built it. See #22

Thx David! I'm gonna test it and give you a feedback! :)

**Comment by ciesinsn** [comment]
closing issue now that feature has been merged.  Thanks @David00 for the contribution.
