### ISSUE TITLE
Add input validation on installer to avoid iPSK database user and ISE ODBC user to be the same (leads to "Creation of Cisco ISE MySQL user failed")

### ISSUE THREAD

**Issue by AnthoBalitrand** [CiscoDevNet/iPSK-Manager#21]
**Issue**

On installer, if "iPSK database username" and "Cisco ISE ODBC Username" have the same values, the install script indeed tries to create 2 mySQL users with the same username, which leads to the "Creation of Cisco ISE MySQL user failed" error. 
(On backend, mySQL error 1396). 

**Suggested solution**

Add data validation on the installer form to avoid those 2 values to be the same.

**Comment by ciesinsn** [comment]
This will be added in the next commit.

**Comment by ciesinsn** [comment]
changes have been merged into master branch
