### ISSUE TITLE
iPSK-Manager Fails to create DB 

### ISSUE THREAD

**Issue by sharker-RNIB** [CiscoDevNet/iPSK-Manager#24]
**Describe the bug**
I am installing iPSK-Manager on ubuntu 22.04-LTS Server and cannot create the iPSK Database. 

**To Reproduce**
1. Following the Install readme on Github. I got to the install.php
2. Filled in all details as per suggestions
3. Create Admin Password Click Next 
4. Click Install 
5. Get 500 Error 
**Expected behavior**
should create a DB and continue to install iPSK-Manager 
**Screenshots**
![image](https://user-images.githubusercontent.com/118446877/202446095-fb4fb18d-2ca3-45c0-b893-c45b319e212e.png)
![image](https://user-images.githubusercontent.com/118446877/202446185-79cc9d7e-2add-416b-851d-738c0baf9373.png)
![image](https://user-images.githubusercontent.com/118446877/202446411-f131e1cb-91bc-4162-bee9-5d91b7c9124f.png)
![image](https://user-images.githubusercontent.com/118446877/202446540-7794c539-3dcb-4dd1-88b8-82c21c54a01d.png)
![image](https://user-images.githubusercontent.com/118446877/202446599-19750776-ac3b-4842-9e19-cf5ac7368598.png)
![image](https://user-images.githubusercontent.com/118446877/202446654-f94e7151-0527-41c1-a034-fb8108a7e977.png)
![image](https://user-images.githubusercontent.com/118446877/202446803-e5622d9a-6128-463f-b6a0-10a4d0868272.png)
![image](https://user-images.githubusercontent.com/118446877/202447449-934898dc-6de2-4d75-a403-256263d985eb.png)

**Server (please complete the following information):**
 - OS: 
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=22.04
DISTRIB_CODENAME=jammy
DISTRIB_DESCRIPTION="Ubuntu 22.04.1 LTS"

***Desktop***
OS: Windows 10 22H2 
Browser: Edge
**Additional context**

**Comment by sharker-RNIB** [comment]
I've managed to get iPSK-Manager installed. 
Ubuntu 22.04 comes with PHP 8.1.x the php code in the installer.php file doesn't work very well with php 8.1 I had to "downgrade" the php version back to 7.4.x and install all the 7.4 exentions: 

Downgrade: 
sudo apt install software-properties-common apt-transport-https -y
#install the php 7 repo 
sudo add-apt-repository ppa:ondrej/php -y
sudo apt update
sudo apt upgrade
#install php7 
sudo apt install php7.4 php7.4-common libapache2-mod-php7.4 php7.4-cli
#Disable php 8 
sudo a2dismod php8.1
#Enable php 7 
sudo a2enmod php7.4
#restart Apache2 
sudo systemctl restart apache2
#Install php extentions needed for iPSK-Manager 
sudo apt install php7.4-mbstring
sudo apt install php7.4-xml
sudo apt install php7.4-ldap
sudo apt install php7.4-mysqli
sudo apt install php7.4-mysqlng
sudo apt install php7.4-curl
#I do not know if all those are needed I am using my command history for this 
Then restart apache2 again: 
sudo systemctl restart apache2

After doing this I could then get through the full installer. 

This is not ideal as php7.4 could have issues in it. Ideally iPSK-Manager needs to be updated to php 8

**Comment by htlgit00** [comment]
The exception appears from lines 358 ~ 363 of installer.php 
``` php
			if($dbConnection->select_db($_SESSION['databasename'])){
				$installProgress .= "<div><span style=\"color: #ff0000\" data-feather=\"x-circle\"></span>Database Already Exists</div>";
				goto Bail;
			}else{
				$installProgress .= "<div><span style=\"color: #2d8c32\" data-feather=\"check-circle\"></span>Database is not in use</div>";
			}
```

Likely, this is due to this change [PHP RFC: Change Default mysqli Error Mode](https://wiki.php.net/rfc/mysqli_default_errmode), which reported in PHP 8.1.

**Comment by ciesinsn** [comment]
This specific issue (lines 358-363 above) has been fixed and working on another fix or two before pushing it up to the branch.

**Comment by ciesinsn** [comment]
changes have been merged into master branch
