### ISSUE TITLE
Is this still being developed?

### ISSUE THREAD

**Issue by GD-Dal** [CiscoDevNet/iPSK-Manager#25]
Is it?
There are some issues that should be looked into

Thanks

**Comment by garns78** [comment]
2nd this, please can this be updated to support php8

Thanks

**Comment by ciesinsn** [comment]
Short answer is, yes.  @garns78 do you have specific items you've found not working with php8?  I have a fix for one done and working on another for initial installation.

**Comment by garns78** [comment]
Thanks, firstly, customer is sensitive about using unsupported versions. i.e rollback to php 7.4 required for installation.

Secondly we are having huge issues connecting to customer AD using LDAPS. Any support on this would be greatly appreciated.

**Comment by ciesinsn** [comment]
@garns78, funny enough AD/LDAPS was the item I am currently looking at and my hope is after that I'll push all the changes unless I find something else that needs to be corrected for php8.

**Comment by ciesinsn** [comment]
@garns78 changes for php8 have been merged into master.  If you still have LDAP issues please open a new issue with details of the issue.  Note, I added two lines of code to BaseLDAPClass.php where you can uncomment them and it won't enforce a certificate validation if that is your issue.
