### ISSUE TITLE
LDAPS failed

### ISSUE THREAD

**Issue by garns78** [CiscoDevNet/iPSK-Manager#26]
Hi there,

Please could you help us with LDAPS. In the iPSK app we get "failure" but are unable to work out why.

We have tried using the ldapsearch tool with the following result.

Thanks in advance

ldap_sasl_bind
ldap_send_initial_request
ldap_new_connection 1 1 0
ldap_int_open_connection
ldap_connect_to_host: TCP cutomerserver.LOCAL:636
ldap_new_socket: 3
ldap_prepare_socket: 3
ldap_connect_to_host: Trying serverip:636
ldap_pvt_connect: fd: 3 tm: -1 async: 0
attempting to connect: 
connect success
tls_write: want=407, written=407

 ---- cert --
   
**tls_read: want=5 error=Connection reset by peer
TLS: can't connect: Error in the pull function..
ldap_err2string
ldap_sasl_bind(SIMPLE): Can't contact LDAP server (-1)**

**Comment by ciesinsn** [comment]
@garns78 Can you uncomment lines 99 and 122 in BaseLDAPClass.php and see if it works?  Those lines being uncommented would stop the LDAP connection validation of the certificates.  This would rule out a issue with the CA being trusted.

**Comment by ciesinsn** [comment]
@garns78 Did you try what I put in the last message?  If so did it solve the issue?

**Comment by ciesinsn** [comment]
@garns78 closing this issue due to lack of response
