### ISSUE TITLE
Doku is reffering to an Appendix

### ISSUE THREAD

**Issue by VidaRD1234** [CiscoDevNet/iPSK-Manager#28]
**Describe the bug**
Step 8. says the following:
_It is recommended to use SSL for security and subsequent section describes how to enable SSL. However, if no certificate is available,**follow the instructions in the Appendix** on how to use non-SSL port for the portals_

There are no Appendixes as far as I can see.

**Comment by ciesinsn** [comment]
Thanks for the call out on that.  It looks like that part of the document wasn't moved over to GitHub from its old location.  If you needed the Appendix section sooner then I get it update in GitHub here is the old link where it is found.

https://community.cisco.com/t5/security-knowledge-base/ipsk-identity-pre-shared-key-manager-portal-server-for-ise/ta-p/3904265
