### ISSUE TITLE
Filtering and additional columns on Endpoint List Page

### ISSUE THREAD

**Issue by joe-catanzaro** [CiscoDevNet/iPSK-Manager#31]
**Is your feature request related to a problem? Please describe.**
When looking at the list of all endpoints, I'm unable to filter by any of the heading fields.  I have to search, which then brings up the endpoints I'm looking for, but the search resets when I go back to the list.  I also can't see who created each endpoint without clicking the 'view' button.

**Describe the solution you'd like**
Filtering ability for each of the column headings, and added columns for full name or email address for the user that created each endpoint record.

**Describe alternatives you've considered**

**Additional context**

**Comment by joe-catanzaro** [comment]
I've also gotten a suggestion from one of the users managing devices in the portal that having description as a column would be helpful.  He's got a bunch that he has to go in and delete, but he can't search by the description to figure out which is which.  he has to click into view each one before he can determine what it is.

**Comment by ciesinsn** [comment]
> I've also gotten a suggestion from one of the users managing devices in the portal that having description as a column would be helpful. He's got a bunch that he has to go in and delete, but he can't search by the description to figure out which is which. he has to click into view each one before he can determine what it is.

In fix #22 the ability to search by name, email, and even description was added but those columns don't show on the screen. Do you still think you need to see the values?  The thought was it may get to become too much data showing on the screen.

For filtering on columns I am working on adding that in addition to the complete table search/filter that was added in #22.

**Comment by Jumb0Fr4m3** [comment]
We would also like to have the description field showing up on screen as we are currently using that to enter what type of equipment is registered.
Would it be possible to show/hide it, if you consider it to be to much info on the screen?

**Comment by ciesinsn** [comment]
@Jumb0Fr4m3 In dev-saml-support branch I added the ability to choose columns to show, if you wanted to check it out.  This will allow you to make visible the hidden columns, specifically the description field.  This other branch will be merged to the main branch soon.

**Comment by ciesinsn** [comment]
Closing issue with merge of dev branch into main branch that has column selector added

**Comment by Jumb0Fr4m3** [comment]
It's working superb from the "Managed iPSK EndPoints" but when I click Column visibility from a portal (Manage Associations)  it just shows these entries to choose from:

MAC Address
Endpoint Group
Expiration Date
View
Actions

I'm not able to choose description.

**Comment by ciesinsn** [comment]
Can you make a new issue for an enhancement on the sponsor portal to add the additional columns? 

The work to add the extra columns several months ago was only done on the admin portal and I'll have to work to pull that into the sponsor portal as well.
