### ISSUE TITLE
Add ability to search endpoint list by attributes, including MAC address, name and email to the Sponsor Portal 

### ISSUE THREAD

**Issue by ismavislb** [CiscoDevNet/iPSK-Manager#32]
**Is your feature request related to a problem? Please describe.**
The ability to search the endpoint list by attributes on the admin portal was added on fix#19. However, there are no filtering/search options on Sponsor Portals (manage.php). Sponsors struggle to find endpoints through the portal as the list goes bigger.

**Describe the solution you'd like**
Please, add endpoint search and sorting option by attributes (MAC address, name, email) to Sponsor Portal. 

**Describe alternatives you've considered**

**Additional context**

**Comment by ciesinsn** [comment]
@ismavislb I'll be pushing this enhancement in the next commit.

**Comment by ismavislb** [comment]
@ciesinsn Worked like a charm. Thank you!
