### ISSUE TITLE
First endpoint created in a new deployment does not show up in the endpoint list.

### ISSUE THREAD

**Issue by David00** [CiscoDevNet/iPSK-Manager#33]
This is an issue stemming from my PR (#22) which added searchable tables to the endpoint list.

In a brand new iPSK Manager deployment, the first endpoint you create will not show up in the table, at all. The next endpoint, and all future endpoints will show up, but the first one never will. (Technically, it _did_ show up, but it was showing up as "Suspended" with no other details. I "fixed" it in dd68cc3a05bbed2dbd6361461cff6daba0287bba by hiding the Suspended entry as described here: https://github.com/CiscoDevNet/iPSK-Manager/pull/22#issuecomment-1162393821)

This was a mis-diagnosis of the root cause - it turns out, my pagination implementation [removed the `$pageStart` variable](https://github.com/CiscoDevNet/iPSK-Manager/pull/22/files#diff-75bf743e934dff296c98a813d8c24cc710c2d0535f252607b77b3b9aef0fff87L56-L65), which is [referenced ](https://github.com/CiscoDevNet/iPSK-Manager/blob/master/supportfiles/adminportals/modules/endpoints/endpoints.inc.php#L39)when initializing the loop that builds the endpoint table.

PR with fix coming shortly.

**Comment by ismavislb** [comment]
Merged my test deployment with David00/iPSK-Manager master and also started brand new IPSK deployment and it worked like a charm. Thanks David. It would be really good to see similar endpoint searching and sorting options for Sponsor Portals too. We don't provide sponsors access to the admin portal and just to portals marked as "Sponsor" type, which makes it very difficult for sponsors to manage the associations they create as the endpoint list goes bigger. I have requested enhancement on issue#32

**Comment by David00** [comment]
> Successfully merged test deployment and started brand new IPSK deployment and it worked like a charm (with David00/iPSK-Manager master). Thanks @David00. It would be really good to see similar endpoint searching and sorting options for Sponsor Portals too (manage.php). We don't provide sponsors access to the admin portal and just to portals marked as "Sponsor" type, which makes it very difficult for sponsors to manage the associations they create as the endpoint list goes bigger. I have requested enhancement on issue#32

Awesome, thanks for testing! I like the idea of bringing the same endpoint table functionality to the sponsor portal section. I'd be happy to take a look at that and put forth a PR to implement it much the same way I did with the admin portal endpoint list (time permitting, of course!)
