### ISSUE TITLE
Admin Portal loop on fresh install

### ISSUE THREAD

**Issue by larsrei** [CiscoDevNet/iPSK-Manager#4]
Hello,

I installed the tool to a new server. I configured mysql and apache. When I start the adminportel, I see a loop. Url is append de-DE and than next de-DE and so go on.
`https://<ip address>/de-DE/de-DE/de-DE/de-DE/de-DE/de-DE/de-DE/de-DE/de-DE/de-DE/de-DE/de-DE/de-DE/de-DE/de-DE/de-DE/de-DE/de-DE/de-DE/de-DE/de-DE/de-DE/index.html`
How can I debug this and where is the error?

Apache config:
`
<IfModule mod_ssl.c>
<VirtualHost *:443>
ServerAdmin webmaster@ipskmanager
DocumentRoot /var/www/iPSK-Manager/adminportal
<Directory /var/www/iPSK-Manager/adminportal>
AllowOverride All
</Directory>
ErrorLog /var/log/httpd/admin-error.log
CustomLog /var/log/httpd/admin-access.log combined

SSLCertificateFile /etc/httpd/ssl/psk-portal-dev.crt
SSLCertificateKeyFile /etc/httpd/ssl/psk-portal-dev.key

SSLCertificateChainFile /etc/httpd/ssl/psk-portal-dev.chain

<FilesMatch "\.(cgi|shtml|phtml|php)$">
SSLOptions +StdEnvVars
</FilesMatch>

</VirtualHost>
</IfModule>
`

best regards,
Lars

**Comment by offroad99** [comment]
I have installed multiple times without this issue. Are you simply navigating to https://<ip address> and seeing this issue?

**Comment by larsrei** [comment]
Yes I only navigate to https://<name> and than I see this issue.

**Comment by cisco-garyoppel** [comment]
Are you able to share the details from the Apache configuration for the Directory declaration to confirm directory permissions and settings are correct?
