### ISSUE TITLE
Not able to login with LDAPS

### ISSUE THREAD

**Issue by Jumb0Fr4m3** [CiscoDevNet/iPSK-Manager#44]
After the latest install I am not able to login with LDAP(S) anymore.
The error message I get is this:

PHP Notice:  Undefined variable: authorizedGroups in /var/www/iPSK-Manager/adminportal/login.php on line 135, referer:

To reproduce:
From login page: Type username and password and choose the configured LDAPS server as source.
Click Sign In.

LDAPS connection is working. When clicking Test on the Connection name (under LDAP servers) it reports success.

**Comment by Jumb0Fr4m3** [comment]
This is an existing one I overwrite with git pull.

**Comment by ciesinsn** [comment]
When is the last time you did a pull?  The login.php page you mentioned above hasn't been modified since commit d2abed2 which was a week ago.  Are you sure you have your groups configured correctly and are a member of one allowed for admin portal management?

**Comment by Jumb0Fr4m3** [comment]
I'll try to do some more testing. The strange thing is that logging intoSponsor Portals are working fine with LDAPS. It's only the Admin Portal that is not working anymore.

**Comment by Jumb0Fr4m3** [comment]
![image](https://github.com/CiscoDevNet/iPSK-Manager/assets/101570225/7d2acb85-cedb-4791-a9fb-2f66fd8a7165)

Did some testing. When using the Login.php from the version "php8 and other fixes" is working.
When I try to use the login.php from "SAML Admin Portal Support" I get the error.
Not sure if that is helpful.
Is there any more logging I can turn on to narrow it down?

**Comment by Jumb0Fr4m3** [comment]
https://x.x.x.x/index.php?error=3

**Comment by ciesinsn** [comment]
Oh, and  forgot, there is a logging table as well, can you dump out any logs from the time period.  Don't think it will be much help for me, but just incase.

**Comment by Jumb0Fr4m3** [comment]
Well the problem is that the Platform Configuration is also broken after the update. That probably is another error.
Only get a blank page when clicking on it
The admin-error log says:

[Thu May 02 15:30:34.873628 2024] [php7:error] [pid 5305] [client x.x.x.x:21729] PHP Parse error:  syntax error, unexpected '' (T_ENCAPSED_AND_WHITESPACE), expecting '-' or identifier (T_STRING) or variable (T_VARIABLE) or number (T_NUM_STRING) in /var/www/iPSK-Manager/supportfiles/adminportals/modules/sysconfig/general.inc.php on line 97, referer: https://x.x.x.x/adminportal.php

Can you share the sql command to get the neccessary info from the db?

**Comment by ciesinsn** [comment]
Did you copy your config.php someplace else before you did the git pull and put it back?  It almost seems like you are missing files or some files didn't get updated right from a pull.

As for MySQL

Once on the DB CLI after logging in.

use <db name>;
select * from settings;

**Comment by ciesinsn** [comment]
What version of PHP are you running on your setup?

**Comment by Jumb0Fr4m3** [comment]
seems to be PHP 7.2.34

**Comment by ciesinsn** [comment]
Any way you can bump that up to 8.0?  I am wondering if this is the issue at hand as that above error on the general.inc.php points to a line where I see comments about whats done there not working with PHP 7.2 and wonder if maybe something else with login is PHP version related as well since I'm using PHP 8.0.  May have to change what is mentioned as possible PHP versions if that is the case.

**Comment by ciesinsn** [comment]
Looks like for sure the general.inc.php error is related to PHP version as this comment is what that line is doing where it says PHP less then 7.3 will cause a error.   This I can correct but now really have be wondering if the LDAP issue is also related to PHP version. 

<img width="1057" alt="image" src="https://github.com/CiscoDevNet/iPSK-Manager/assets/37383749/96aad120-03d6-4626-90c4-4decb7710a43">

**Comment by Jumb0Fr4m3** [comment]
Thanks. I will try to upgrade it to 8 tomorrow. Will let you know the outcome.

**Comment by Jumb0Fr4m3** [comment]
I have upgraded to php8 but still get an error. But a new error line:

[Fri May 03 12:33:48.507569 2024] [php:warn] [pid 1960] [client 10.251.8.6:33859] PHP Warning:  Trying to access array offset on value of type bool in /var/www/iPSK-Manager/adminportal/login.php on line 64, referer: https://x.x.x.x/index.php?error=3
[Fri May 03 12:33:48.520884 2024] [php:warn] [pid 1960] [client x.x.x.x:33859] PHP Warning:  Undefined variable $authorizedGroups in /var/www/iPSK-Manager/adminportal/login.php on line 135, referer: https://x.x.x.x/index.php?error=3


Heres the screenshot of the Platform Configuration (probably working again after upgrade to php8)

![image](https://github.com/CiscoDevNet/iPSK-Manager/assets/101570225/648d2afd-f63d-4e46-a911-2eba9b186ad5)

**Comment by ciesinsn** [comment]
Can you send me a photo of the groups page as well?

**Comment by Jumb0Fr4m3** [comment]
![image](https://github.com/CiscoDevNet/iPSK-Manager/assets/101570225/3614c03f-abb5-4108-a5dd-e92e14729c88)

**Comment by ciesinsn** [comment]
And I assume the user you are logging in with is a member of that 2nd group or the last group and your selecting the ldap directory those groups are in when you login, correct? They are the only ones that would allow login to the admin portal as configured. 

If the above is true can you go back to the portal configuration page and check the option for enable nested groups and then press update settings. Uncheck the box and then do update settings again. Logout and try and login again. 

If you still have an issue do the same thing above but this time check use ldap for admin portal authorization in the SAML area as the item you check and uncheck.  

Doing those steps will put some settings in that database table you sent the image of yesterday. Those settings are referenced in the login.php code for all portals. 

Everything with the login should work without them and I verified in my setup it did yesterday, I'm curious though if this is what is causing the issue for you.

**Comment by Jumb0Fr4m3** [comment]
Did what you suggested but still no success:
My database got some extra columns added:

![image](https://github.com/CiscoDevNet/iPSK-Manager/assets/101570225/19bc286f-5fd8-464a-bbcc-d04622421b59)

**Comment by ciesinsn** [comment]
Ok, good in a way as I expected it to not be hung up on that. 

That line 135 error is time matched to when you try and login via ldap? You're sure of that? Can you tail your error log to make sure it does appear at the time of ldap login failure?

You'd only get to that line if doing a local login, not ldap. The similar line you'd get to from a ldap login is further down in the code. 

That entire code block runs when the submitted login form has a value of 0 for the chosen user source in the drop down on the login page.  

A error of 3 means unable to authenticate, bad user name or password. 

Are you able to post the source html you see on your login screen?

**Comment by Jumb0Fr4m3** [comment]
The 135 does occur when I try to logon. I have verified that.
I have verified that I get to that code both when I try to unsuccessful try to logon local and also when I try to logon through LDAPS

Is this the html you're wanting?

<!doctype html>
<html lang="en">
  <head>
    	<meta charset="utf-8">
    	<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    	<meta name="description" content="">
    	<meta name="author" content="">
    	<link rel="icon" href="../../../../favicon.png">

    	<title>iPSK Manager for Cisco ISE</title>

    	
    	<link href="styles/bootstrap.min.css" rel="stylesheet">

    	
    	<link href="styles/signin.css" rel="stylesheet">
  	</head>
	<body class="text-center">
		<div class="card mx-auto">
			<div class="card-header bg-primary mb-4">
  				<img src="images/ipsk-logo.gif" width="180" height="32" />
			</div>
			<div class="card-body">
				<h1 class="h4 mt-0 mb-4 fw-normal">iPSK Manager for Cisco ISE</h1>
				<h2 class="h5 mt-0 mb-4 fw-normal">Please Login</h2>
								<div class="col">
						<div class="alert alert-danger shadow" role="alert">Authentication Failed</div>
					</div>
							<form action="login.php" method="post" class="form-signin">
					<label for="inputUsername" class="visually-hidden">Username</label>
					<input type="text" name="inputUsername" id="inputUsername" class="form-control mt-2 mb-3 shadow" placeholder="Username" required autofocus>
					<label for="inputPassword" class="visually-hidden">Password</label>
					<input type="password" name="inputPassword" id="inputPassword" class="form-control mt-2 mb-3 shadow" placeholder="Password" required>
			Please select an Authentication Source:<select name="authDirectory" class="form-select mt-2 mb-3 shadow"><option value="0">Internal</option><option value="5" selected>LDAPS</option><option value="6">LDAPS#2</option></select>					<button class="btn btn-primary btn-block mt-2 mb-3 shadow" id="loginbtn" type="submit">Sign in</button>
				</form>
			</div>
			<div class="card-footer">
				Copyright &copy; 2024 Cisco and/or its affiliates.
			</div>
		</div>
	</body>
</html>

**Comment by ciesinsn** [comment]
If you go to the ui-refresh-sponsor-portal branch and pull the login.php from that branch I think it should work.  You can also pull the entire branch if you want.

**Comment by Jumb0Fr4m3** [comment]
Thanks. Now it's working perfectly again. Thanks for the great help on this.

**Comment by ciesinsn** [comment]
Glad to hear, wish I wasn't as blind at the beginning :)

**Comment by ciesinsn** [comment]
@Jumb0Fr4m3 You may want to do a new pull.  I noticed in one of your images above a alignment issue but didn't know if it was just your browser window size.  I experienced the issue myself and realized there was a alignment issue under certain conditions.  I fixed it so if you pull again your admin screens will line up right :)
