### ISSUE TITLE
Port enhancement from commit 458bc66 and issue #30 to the sponsor portal pages

### ISSUE THREAD

**Issue by joe-catanzaro** [CiscoDevNet/iPSK-Manager#46]
**Is your feature request related to a problem? Please describe.**
The fix for the illegal character handling that was applied to the admin portal needs to be applied to the other portals as well.

**Describe the solution you'd like**
Per Nick, Port enhancement from commit 458bc66 and issue #30 to the sponsor portal pages

**Describe alternatives you've considered**
No real other alternative.

**Comment by ciesinsn** [comment]
This enhancement was ported over to the sponsor portal and should now be in the main branch.  Closing this issue :)
