### ISSUE TITLE
Add SAML / Shibboleth Support

### ISSUE THREAD

**Issue by slivesay30** [CiscoDevNet/iPSK-Manager#5]
It would be nice to have SAML / Shibboleth support for IPSK Manager.  We have a company policy that requires apache and iis servers to use SSO authentication for users.  This can be done via basic apache auth and using shibboleth plugin.  Once authenticated user info can be looked up in AD via SLDAP or via the shibboleth headers.

We are trying to utilize a common SSO page and authentication process for corporate users to help decrease confusion for untrusted sites.  

Please see shibboleth site:  https://www.shibboleth.net/community/

**Comment by dresken** [comment]
+1 for SSO.

**Comment by ciesinsn** [comment]
So I am starting to work on SAML support and I think the easiest way to do that is to rely on the application not being the SP. Where either a module, such as the Apache Shibboleth module acts as the SP and sets environment variable(s) the app will use, or, something outside of a module is the SP and headers are set for the app to use.  Obviously, headers add risk if your SP isn't set to strip incoming headers that it sets but thinking it provides flexibility to provide both as options. 

My thought is for at least the first pass at this it would still require users to be defined in either the internal user db or a connected ldap server for group mapping.  This I feel would require less modifications to the existing base code and be quicker to implement to get SAML support in at least some form in the app.  I already have some base modifications in the admin portal complete and working in a crude way.

**Comment by slivesay30** [comment]
I would think you can just use the saml attributes to map "AD" users in the request.  This is normally how we use saml in other apps.
________________________________

**Comment by ciesinsn** [comment]
@dresken @slivesay30 You can try a preview for SAML support for admin portal only (at this time) by pulling from the dev-saml-support branch.  Would help if you can try it out and provide feedback.

**Comment by ciesinsn** [comment]
You can actually test sponsor and captive portal SAML support as well. It was quicker to add support for those portals than I thought.  Barring any issues you find I believe it's ready for pushing to the main branch other then improving the readme on how to configure Apache for mod_shib.
