### ISSUE TITLE
unable to reference accountEnabled attribute 

### ISSUE THREAD

**Issue by ognetravco** [CiscoDevNet/iPSK-Manager#50]
I am unclear on how to reference the "accountEnabled" attribute. 

If i suspend the endpoint, ISE still lets it on the network. If I add the iPSK manager attribute "accountEnabled = 1" to the authorization policy that is already looking for the endpoint's device group, the rule stops working.

How do i get this to work?

Using the following.
iPSK_AuthMACPlainNonExpired
iPSK_FetchPasswordForMACNonExpired
iPSK_MACLookupNonExpired

Ubuntu 22.04.4 LTS
MySQL 8.0.36-0ubuntu0.22.04.1
PHP 8.1.2-1ubuntu2.17
ISE 3.2.0.542 patch 3.4

**Comment by ciesinsn** [comment]
Can you include a screenshot of your ISE authz policy as well as the live log details for the endpoint?  I can check it out and try and reproduce.

**Comment by ciesinsn** [comment]
Are you using accountEnabled or accountExpired?  I didn't catch you said accountEnabled initially and believe it should be accountExpired as that is what is returned in the attribute SQL procedure.

**Comment by ciesinsn** [comment]
So, accountEnabled is not sent back to ISE in the SQL procedure call.  The attribute that is is accountExpired which is True if its time expired and False if it is not time expired.   For a suspended endpoint when it runs any of the procedures you have above it will return authentication error.

**Comment by ciesinsn** [comment]
I think the confusion is the original authors documentation on the Cisco communities doesn't cover what you are looking to do and actually doesn't have iPSK Manager as part of the authentication flow, just authorization.  I really should work on getting all that documentation moved over to GitHub and cleaned up.

If you make a authentication rule for your MAB authentication that uses the iPSK ODBC database vs the Internal Database like this I think it will do what you are looking for when a endpoint is suspended if I'm following what you're asking.

<img width="1271" alt="image" src="https://github.com/CiscoDevNet/iPSK-Manager/assets/37383749/68ba9c09-0d10-4f90-a9f6-86a1564a042e">

**Comment by ciesinsn** [comment]
One additional item I didn't mention you may want to switch to using the versions of the procedure that don't have "NonExpired" in the name.  When you use ones with "NonExpired" in the name if the endpoint is expired they will be returned with a authentication error and then wouldn't connect to the SSID. 

The ones without "NonExpired" would return authentication success and If you wished to allow them to re-enroll/renew a registration you'd then use the accountExpired attribute in a AuthZ rule.

**Comment by ognetravco** [comment]
I appreciate the clarification that ISE does not receive the attribute as part to the authorization. The intent was to be able to disable certain endpoints on the iPSK Manager Admin portal to deny access but still retain the endpoint in the database. But removing the endpoint or placing it in a "Disabled" group that has no ISE policy would result in the same action of access being denied.

Not part of the original question so I'm ok with not getting answer, but when exactly does the accountExpired attribute goes from False to True? I shutdown my test iPSK Manger VM over the weekend an the entry that should be expired, show expired on the portal but the data base still has it as accountExpired=False.

**Comment by ognetravco** [comment]
Appreciate the detail feedback, totally makes sense now 😄
