### ISSUE TITLE
Endpoint expiration email alert

### ISSUE THREAD

**Issue by ognetravco** [CiscoDevNet/iPSK-Manager#52]
My use case for iPSK Manager is to allow other technicians to have a self-service portal to onboard their endpoints that only have a PSK option for wireless access.

The enhancement I would like to see is having a daily schedule event that would run at a designated time [like a cron job] to look for endpoints that would be expiring soon. The expiration criteria would preferably be customizable, like 5 days before expiration send an email. Maybe even have the ability to customize the alert being sent with a button to send a test email.

This enhancement would help to minimize down time as device that still need access can have their expiration date extended. This would also help to clean up the database as device no longer needing access can be purged.

**Comment by ciesinsn** [comment]
This enhancement will be pulled into the master branch shortly.  If you'd like to test before its in the nov24 branch.
