### ISSUE TITLE
VLAN Assignment

### ISSUE THREAD

**Issue by Murmucka** [CiscoDevNet/iPSK-Manager#56]
VLAN Assignment in iPSK Manager to assign it dynamically in ISE based on Device Group in iPSK Manager

**Comment by ciesinsn** [comment]
Are you looking to be able to enter a VLAN when defining a Device Group and have that VLAN be returned in the FetchGroups stored procedure ISE calls?

**Comment by Murmucka** [comment]
> Are you looking to be able to enter a VLAN when defining a Device Group and have that VLAN be returned in the FetchGroups stored procedure ISE calls?

Yes, so with this solution i have then dynamic VLAN assignment possible, and i dont need to set up for each a separate policy result

**Comment by ciesinsn** [comment]
This is a interesting request after thinking about it.  If iPSK Manager would define VLAN and even dACL values it could be used in a similar way for wired ports with authentication, ignoring the iPSK value.   I'm thinking this may be better placed within the Authorization Template as optional elements.  I'll add it to the list :)

**Comment by ciesinsn** [comment]
This enhancement will be pulled into the master branch shortly.  If you'd like to test before, its in the nov24 branch.
